sudo: false
language: python
python:
- "2.7"
addons:
    apt:
        packages:
            - make
            - gcc
            - python-virtualenv
            - unzip
            - gcc-multilib
before_script:
- "cd .."
# make virtual env
- "python /usr/lib/python2.7/dist-packages/virtualenv.py virtualenv;"
- "cd virtualenv;"
- "source bin/activate;"
# install tcc
- "git clone http://repo.or.cz/tinycc.git tinycc && cd tinycc && git checkout d5e22108a0dc48899e44a158f91d5b3215eb7fe6"
- "./configure --disable-static --tccdir=./ --libdir=$(pwd) --includedir=$(pwd)"
- "make && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd);cd ..;"
- "cp tinycc/libtcc.h include"
- "cp tinycc/libtcc.so.1.0 tinycc/libtcc.so"
# install elfesteem
- "git clone https://github.com/serpilliere/elfesteem elfesteem && cd elfesteem && python setup.py install && cd ..;"
# install pyparsing
- "pip install pyparsing"
# install miasm
- "cd ..;git clone https://github.com/cea-sec/miasm miasm && cd miasm;"
- "python setup.py build build_ext -I$(pwd)/../virtualenv/include -L$(pwd)/../virtualenv/tinycc"
- "python setup.py install"
- "cd ..;"
# get tests
- "git clone https://github.com/commial/Sibyl-tests sibyl-tests;"
# prepare env
- "export SIBYLTEST=$(pwd)/sibyl-tests"
- "export SIBYL=$(pwd)/Sibyl;"
script:
- "cd $SIBYL/c_tests && python run_ctests.py;"
- "cd $SIBYL/c_tests && python run_ctests.py -f -a;"
- "cd $SIBYLTEST && ./run.sh;"
